CREATE TABLE Yields (
    game_id VARCHAR(255),
    turn INT,
    player_id INT,
    num_cities INT,
    population INT,
    techs INT,
    civics INT,
    land_units INT,
    corps INT,
    armies INT,
    naval_units INT,
    tiles_owned INT,
    tiles_improved INT,
    gold_balance INT,
    faith_balance INT,
    science_per_turn INT,
    culture_per_turn INT,
    gold_per_turn INT,
    faith_per_turn INT,
    production_per_turn INT,
    food_per_turn INT,
    PRIMARY KEY (game_id, turn, player_id)
);